name: "GQ GMC"
description: "Nuclear radiation sensor using serial"
version: "1.0.23"
slug: "gq-gmc"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

devices:
  - "/dev/ttyUSB0"

options:
  GMCport: /dev/ttyUSB0
  GMCbaudrate: 115200
  GMCtimeout: 3
  UpdateInterval: 10
  LogLevel: DEBUG
schema:
  GMCport: str
  GMCbaudrate: "list(57600|115200)"
  GMCtimeout: "int(1,30)"
  UpdateInterval: "int(1,600)"
  LogLevel: list(CRITICAL|ERROR|WARNING|INFO|DEBUG)